Replace heavyweight aws-java-sdk with fine-grained plugin
jenkinsci/s3-plugin pull request #137
Opened 2021-09-30 13:11 UTC by Vlatombe

Since 1.12.70, the `aws-java-sdk` plugin has been split into multiple fine-grained plugins.

This pull request replaces the heavyweight `aws-java-sdk` (195Mb) with a smaller `aws-java-sdk-minimal` dependency.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-10-01 15:28 UTC, Vlatombe commented
Ping @alecharp

2021-10-04 07:30 UTC, alecharp requested changes
Just to use the latest version of Maven plugin and of the Parent POM. 
Thanks.

2021-10-04 07:30 UTC, alecharp commented on pom.xml
> +        <version>4.25</version>
```suggestion
        <version>4.27</version>
```

2021-10-04 07:30 UTC, alecharp commented on pom.xml
> +            <version>3.12</version>
```suggestion
            <version>3.13</version>
```

2021-10-04 08:32 UTC, alecharp approved these changes
Thank you @Vlatombe

2021-10-04 12:16 UTC, merged

2021-10-05 07:00 UTC, Vlatombe commented
Thanks @alecharp, could you cut a release?

2021-10-05 08:36 UTC, alecharp commented
I have test issues locally. Will work on that.